apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8sapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

